### ISSUE TITLE
no file in mustache folder

### ISSUE THREAD

**Issue by he-sk** [wbyoko/tweetdeck-clear-column#1]
Hi,

I recently updated Tweetdeck from the App Store to version 3.9.583-a956295 and now there is no Javascript file in the mustache folder anymore.

Best,
he-sk

**Comment by wbyoko** [comment]
Pretty sure Tweetdeck is redirecting to the tweetdeck.twitter.com site. Until/unless this changes, this plugin isn't going to work.
